In [ ]:
# Question 1
import numpy as np # a ecrire une fois seulement
tableau = np.array([[10,20,15],[30,40,50]])
print(tableau)
liste = tableau.tolist()
print(liste)
print(type(liste))

[[10 20 15]
 [30 40 50]]
[[10, 20, 15], [30, 40, 50]]
<class 'list'>


In [ ]:
#Question2 
#Méthode 1 avec np.tarce()
matrice1= np.array([[6,12,18],[9,3,27],[18,5,1]])
print(matrice1)
trace = np.trace(matrice1)
print(trace)

[[ 6 12 18]
 [ 9  3 27]
 [18  5  1]]
10


In [ ]:
#Méthode 2

In [19]:
#Question 3
matrice2= np.array([[11,9,32],[100,22,78],[4,15,90]])
print(matrice2)
print(matrice2[matrice2>50])

[[ 11   9  32]
 [100  22  78]
 [  4  15  90]]
[100  78  90]


In [20]:
#Question4
A = np.array([[3,13,30],[4,14,44],[5,15,55]])
B = np.array([[2,12,22],[1,11,11],[6,1,66]])
C= A+B
print(C)

[[  5  25  52]
 [  5  25  55]
 [ 11  16 121]]


In [27]:
#Question5
D=np.mean(C)
print(D) # la moyenne de toute la matrice
E=np.mean(C, axis=1) # donne la moyenne des lignes
F=np.mean(C, axis=0) # donne la moyenne des colonnes 
print(E)
print(F)
G = C - F # on soustrait de chaque element la moyenne de sa colonne 
print(G)

# on utilise np car c'es noté touuut en haut, si j'avais mis numpy en haut fallait mettre .numpy

35.0
[27.33333333 28.33333333 49.33333333]
[ 7. 22. 76.]
[[ -2.   3. -24.]
 [ -2.   3. -21.]
 [  4.  -6.  45.]]
